#!/usr/bin/env python3
"""Generate crates/docling-core/src/mathml/symbols.rs from latex2mathml.

docling-core's HTML export renders formulas through latex2mathml
(`latex2mathml.converter.convert_to_element`), whose symbol table comes from
the `unimathsymbols.txt` shipped in the package plus ~40 hand-written aliases
(`symbols_parser.parse_symbols`). The Rust port (`docling_core::mathml`) must
resolve exactly the same names to the same code points, so the table is
dumped from the installed package rather than re-parsed: run with the pinned
version active (the conformance venv — see scripts/conformance/setup-docling.sh)

    python scripts/dev/gen_mathml_symbols.py > crates/docling-core/src/mathml/symbols.rs

The Unicode `Nd` ranges are emitted alongside: Python's `\\d` in `str`
patterns (the tokenizer's number rule, `NUMBER_PATTERN` in the converter)
matches every decimal digit, not only ASCII.
"""

import sys
import unicodedata

import latex2mathml
from latex2mathml.symbols_parser import parse_symbols


def rust_str(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch.isprintable() and ch != " ":
            out.append(ch)
        else:
            out.append(f"\\u{{{ord(ch):x}}}")
    return '"' + "".join(out) + '"'


def nd_ranges():
    ranges = []
    start = None
    prev = None
    for cp in range(sys.maxunicode + 1):
        if unicodedata.category(chr(cp)) == "Nd":
            if start is None:
                start = cp
            elif cp != prev + 1:
                ranges.append((start, prev))
                start = cp
            prev = cp
    if start is not None:
        ranges.append((start, prev))
    return ranges


def main() -> None:
    symbols = parse_symbols()
    out = sys.stdout
    out.write(
        "//! latex2mathml's symbol table — GENERATED by\n"
        "//! `scripts/dev/gen_mathml_symbols.py`, do not edit by hand.\n"
        "//!\n"
        f"//! Source: latex2mathml {latex2mathml.__version__} (`unimathsymbols.txt`, itself\n"
        "//! from the LaTeX `unicode-math` package, plus the aliases\n"
        "//! `symbols_parser.parse_symbols` adds); values are the upper-case hex\n"
        "//! code point exactly as the Python table stores it (5 digits, so the\n"
        "//! `&#x…;` entities the converter writes match byte for byte).\n"
        "\n"
        "/// `(latex name, hex code point)`, sorted by name for binary search.\n"
        "pub(super) static SYMBOLS: &[(&str, &str)] = &[\n"
    )
    for name in sorted(symbols, key=lambda s: s.encode("utf-8")):
        out.write(f"    ({rust_str(name)}, {rust_str(symbols[name])}),\n")
    out.write("];\n\n")
    out.write(
        "/// Inclusive code-point ranges of Unicode general category `Nd`\n"
        f"/// (unicodedata {unicodedata.unidata_version}) — what Python's `\\d` matches.\n"
        "pub(super) static DECIMAL_DIGIT_RANGES: &[(u32, u32)] = &[\n"
    )
    for lo, hi in nd_ranges():
        out.write(f"    (0x{lo:04X}, 0x{hi:04X}),\n")
    out.write("];\n")


if __name__ == "__main__":
    main()
